### ISSUE TITLE
Inconsistent URL paths (and `www.` for signed-out "Home" page)

### ISSUE THREAD

**Issue by cvan** [Pinecast/pinecast#100]
Only the signed-out homepage is served at `www.`:
* Signed-out "Home" page is https://www.pinecast.com/

Trailing/missing slash inconsistencies:
* "Log In" page is https://pinecast.com/login (no trailing slash)
* "Sign Up" page is https://pinecast.com/signup/ (trailing slash)
* Signed-in "Dashboard" page is https://pinecast.com/dashboard/ (trailing slash)
* Signed-in "Upgrade" page is https://pinecast.com/payments/upgrade (no trailing slash)

**Comment by mattbasta** [comment]
The marketing page is intentionally hosted at www. The other inconsistencies can be fixed.

**Comment by cvan** [comment]
Understood./
