### ISSUE TITLE
Add descriptive page titles to `<title>`

### ISSUE THREAD

**Issue by cvan** [Pinecast/pinecast#101]
Every page has a `<title>` of `Pinecast`:

* https://www.pinecast.com/
* https://pinecast.com/login
* https://pinecast.com/signup/
* https://pinecast.com/dashboard/
* https://pinecast.com/payments/upgrade

**Comment by mattbasta** [comment]
I've added titles to the pages that get the overwhelming majority of traffic. It'll get better as the remaining pages get cleaned up otherwise.
