### ISSUE TITLE
Make signed-in UI responsive at tablet/mobile widths

### ISSUE THREAD

**Issue by cvan** [Pinecast/pinecast#102]
1. Load https://pinecast.com/payments/upgrade
2. 😿 

<img width="830" alt="screen shot 2016-09-19 at 11 27 38 pm" src="https://cloud.githubusercontent.com/assets/203725/18659634/affb4204-7ec0-11e6-84ea-5d8bebf16967.png">
<img width="833" alt="screen shot 2016-09-19 at 11 27 10 pm" src="https://cloud.githubusercontent.com/assets/203725/18659635/b00df80e-7ec0-11e6-83b9-e9a5bcb76bba.png">

**Comment by mattbasta** [comment]
I thought there was a bug with the upgrade page, but I think you need to refresh. Also, your zoom is set to 97%. I built the site to be mostly responsive, bruh:

<img width="454" alt="screen shot 2016-09-21 at 7 19 41 pm" src="https://cloud.githubusercontent.com/assets/279498/18735135/67223b16-8030-11e6-81f6-d1d0005b51a2.png">
<img width="477" alt="screen shot 2016-09-21 at 7 19 53 pm" src="https://cloud.githubusercontent.com/assets/279498/18735136/6724ed20-8030-11e6-9d80-2ddd976d9598.png">
