### ISSUE TITLE
Wrap sections/cards in `<fieldset>` elements (and with consistent paddings)

### ISSUE THREAD

**Issue by cvan** [Pinecast/pinecast#106]
1. Load https://pinecast.com/accounts/settings
2. Notice the forms are wrapped in `<fieldset>`s but they're just `<form>`s in `<div class="card card-block">` elements
3. Also, notice the inconsistent padding for the "Account" section compared to the paddings for the other sections

Proposed solution:
Put the individual `<form>`s in `<fieldset>`s with `<legend>`s and with consistent padding.

![screen shot 2016-09-19 at 11 38 59 pm](https://cloud.githubusercontent.com/assets/203725/18660025/20924dc6-7ec3-11e6-8cab-3f80bd60294a.png)

**Comment by cvan** [comment]
Also, it's a bit odd that the `Change Password` form has elements that are of `100%` but the `Bank Account` and `Credit Card` forms are centred:

![screen shot 2016-09-19 at 11 55 50 pm](https://cloud.githubusercontent.com/assets/203725/18660314/9b5bfcea-7ec4-11e6-81a3-276bbddc18d7.png)

Also, the `Add Payment Account` button is not centred (or even flush with the form's labels + fields) like the `Set Bank Account` button is in the form above:

![screen shot 2016-09-19 at 11 55 50 pm](https://cloud.githubusercontent.com/assets/203725/18660338/b493b5ea-7ec4-11e6-911b-2d611970993c.png)

**Comment by mattbasta** [comment]
None of these things exist anymore
