### ISSUE TITLE
Copy nits for "Account Settings" page

### ISSUE THREAD

**Issue by cvan** [Pinecast/pinecast#107]
* `Passwords must be at least eight characters` should have a period: `Passwords must be at least eight characters.`
* Change `Confirm` to `Confirm Password` (or `Retype Password`)
* `To change your email, enter your new email address.` is a bit redundant/confusing; consider saying `To change your email on file, enter your new email address.`
* `We will send you a confirmation message containing a link that will finalize the process.` could be changed to `Check your inbox for a confirmation email that includes a link you'll need to click to confirm your account change.` (although it's wordier, it's clearer)

![screen shot 2016-09-19 at 11 39 18 pm](https://cloud.githubusercontent.com/assets/203725/18659947/a89fdb76-7ec2-11e6-9643-8d803ed22b44.png)
![screen shot 2016-09-19 at 11 38 59 pm](https://cloud.githubusercontent.com/assets/203725/18659948/a8cc8220-7ec2-11e6-8c7a-c00a2e8746d8.png)

**Comment by cvan** [comment]
Also, `Account Holder Name` is used so, to my point above, I think `Card Holder` should be `Card Holder Name`.

**Comment by cvan** [comment]
* Under the `Timezone` form, the `Selected Timezone` label seems unnecessary (although arguably consistent)
* Change the Stripe URL from `https://stripe.com/connect/account-terms` to `https://stripe.com/connect-account/legal` to save one redirect (before the L10n redirect)

**Comment by mattbasta** [comment]
The card holder field will be updated the next time I bump my deps. The Stripe URL is the one they ask you to use, so I'd rather keep it how it is in case they update the redirect.
