### ISSUE TITLE
"Date of Birth" field's placeholder text is slightly clipped in Chrome on Mac OS X

### ISSUE THREAD

**Issue by cvan** [Pinecast/pinecast#110]
> Mac OS X El Capitan 10.11.2 (15C50)
> Chrome Version 52.0.2743.116 (64-bit)

Notice the last `0` is slightly clipped in the year of the `Date of Birth` field:

<img width="468" alt="screen shot 2016-09-19 at 11 59 21 pm" src="https://cloud.githubusercontent.com/assets/203725/18660418/2197bd08-7ec5-11e6-987e-9eb56639c9a9.png">

**Comment by mattbasta** [comment]
This is gone now
