### ISSUE TITLE
Form labels could use some breathing room

### ISSUE THREAD

**Issue by cvan** [Pinecast/pinecast#111]
https://pinecast.com/login
<img width="379" alt="screen shot 2016-09-20 at 12 00 46 am" src="https://cloud.githubusercontent.com/assets/203725/18660449/54217e44-7ec5-11e6-9e16-b824ba7a1f2f.png">

https://pinecast.com/accounts/settings
<img width="439" alt="screen shot 2016-09-20 at 12 00 34 am" src="https://cloud.githubusercontent.com/assets/203725/18660451/570e6e00-7ec5-11e6-9aa9-a88a3f9ffa18.png">

**Comment by mattbasta** [comment]
This is semi-intentional. I'm refreshing all of the forms soon anyway when I move the new/edit flows to React, so hopefully that will make things dramatically better.

**Comment by cvan** [comment]
> This is semi-intentional.

And by "semi" I assume you mean "not"?

**Comment by mattbasta** [comment]
Believe it or not I actually have some mockups and they kind of look like that.

**Comment by cvan** [comment]
> Believe it or not I actually have some mockups and they kind of look like that.

Totally a move out of Davor's playbook 😆

**Comment by mattbasta** [comment]
New form style is slowly rolling out.
