### ISSUE TITLE
Fix awkward top margins on "Sign Up" page at desktop widths

### ISSUE THREAD

**Issue by cvan** [Pinecast/pinecast#99]
At desktop width the "Sign Up" page has an awkward top margin:

![screen shot 2016-09-19 at 11 14 25 pm](https://cloud.githubusercontent.com/assets/203725/18659374/02c97f34-7ebf-11e6-820e-040c0f17ad39.png)

It's still a tad off on the "Log In" page but not as awkward:

![screen shot 2016-09-19 at 11 14 49 pm](https://cloud.githubusercontent.com/assets/203725/18659372/02b5d79a-7ebf-11e6-8fcb-7c270597fa86.png)

<hr>

They both look fine IMO at mobile widths though:

![screen shot 2016-09-19 at 11 14 28 pm](https://cloud.githubusercontent.com/assets/203725/18659373/02c611d2-7ebf-11e6-873a-7f3bbf5e2f24.png)

![screen shot 2016-09-19 at 11 14 54 pm](https://cloud.githubusercontent.com/assets/203725/18659371/02b5cf7a-7ebf-11e6-8b47-8e6b041f2a53.png)

**Comment by mattbasta** [comment]
Are vh units a thing yet?

**Comment by cvan** [comment]
> Are vh units a thing yet?

yup! even in Safari and the stock "Android Browser," and IE 11 :)
